const weatherConditions = [
  {
    category: "Thunderstorm",
    id: [200, 201, 202, 210, 211, 212, 221, 230, 231, 232],
    description: [
      "Thunderstorm with light rain",
      "Thunderstorm with rain",
      "Thunderstorm with heavy rain",
      "Light thunderstorm",
      "Thunderstorm",
      "Heavy thunderstorm",
      "Ragged thunderstorm",
      "Thunderstorm with light drizzle",
      "Thunderstorm with drizzle",
      "Thunderstorm with heavy drizzle",
    ],
    imgSrc: [
      "/./src/assets/images/WCRaincoat.png",
      "/./src/assets/images/WCWaterproofShoes.png",
    ],
    item: "rain protection - just in case!",
  },
  {
    category: "Drizzle",
    id: [300, 301, 302, 310, 311, 312, 313, 314, 321],
    description: [
      "Light intensity drizzle",
      "Drizzle",
      "Heavy intensity drizzle",
      "Light intensity drizzle rain",
      "Drizzle rain",
      "Heavy intensity drizzle rain",
      "Shower rain and drizzle",
      "Heavy shower rain and drizzle",
      "Shower drizzle",
    ],
    imgSrc: [
      "/./src/assets/images/WCRaincoat.png",
      "/./src/assets/images/WCUmbrella.png",
    ],
    item: "rain protection - just in case!",
  },
  {
    category: "Rain",
    id: [500, 501, 502, 503, 504, 511, 520, 521, 522, 531],
    description: [
      "Light rain",
      "Moderate rain",
      "Heavy intensity rain",
      "Very heavy rain",
      "Extreme rain",
      "Freezing rain",
      "Light intensity shower rain",
      "Shower rain",
      "Heavy intensity shower rain",
      "Ragged shower rain",
    ],
    imgSrc: [
      "/./src/assets/images/WCRaincoat.png",
      "/./src/assets/images/WCUmbrella.png",
      "/./src/assets/images/WCWaterproofShoes.png",
    ],
    item: "rain protection - just in case!",
  },
  {
    category: "Snow",
    id: [600, 601, 602, 611, 612, 613, 615, 616, 620, 621, 622],
    description: [
      "Light snow",
      "Snow",
      "Heavy snow",
      "Sleet",
      "Light shower sleet",
      "Shower sleet",
      "Light rain and snow",
      "Rain and snow",
      "Light shower snow",
      "Shower snow",
      "Heavy shower snow",
    ],
    imgSrc: [
      "/./src/assets/images/WCScarf.png",
      "/./src/assets/images/WC Gloves.png",
      "/./src/assets/images/WCWaterproofBoots.png",
      "/./src/assets/images/WCBeanie.png",
    ],
    item: "warmest clothes!",
  },
  {
    category: "Atmosphere",
    id: [701, 711, 721, 731, 741, 751, 761, 762, 771, 781],
    description: [
      "Mist",
      "Smoke",
      "Haze",
      "Sand/dust whirls",
      "Fog",
      "Sand",
      "Dust",
      "Ash",
      "Squalls",
      "Tornado",
    ],
    imgSrc: ["/./src/assets/images/WCScarf.png"],
    item: "highest visibility clothing!",
  },
  {
    category: "Clear",
    id: [800],
    description: ["Clear sky"],
    imgSrc: ["/./src/assets/images/WCScarf.png"],
    item: "finest fashions! It'll be a clear day!",
  },
  {
    category: "Clouds",
    id: [801, 802, 803, 804],
    description: [
      "Few clouds: 11-25%",
      "Scattered clouds: 25-50%",
      "Broken clouds: 51-84%",
      "Overcast clouds: 85-100%",
    ],
    imgSrc: ["/./src/assets/images/WCScarf.png"],
    item: "bright colours. While the skies are grey, you can brighten the day!",
  },
];
export default weatherConditions;
